language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install: pip install -e .
cache: pip
script:
  - nosetests --cover-erase --cover-package=stddomain --with-coverage

after_success:
  - coveralls
